version: '3.8'

services:
  app:
    image: node:18
    container_name: flight-management-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: ${MONGODB_URI}
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET}
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6
    container_name: flight-management-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: redis:7
    container_name: flight-management-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
